title: hi, i'm starlight or something # name of the site
author: lumia # name of site's author
email: lumia@mit.edu # email of site's author
url: https://iam.lumia.gay # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  lumia's impulsively-bought domain that she will use for various things

#permalink: what

favicon: "favicon.ico" # name+extension of favicon (which must be put on the root folder)
goat_counter: lumiaisgay # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "<-" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
